import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { SetStateAction, use, useEffect, useState } from "react";
import { Repository } from "@/type/Repository";
import Repos from "@/component/Repos";
import Pagination from "@/component/Pagination";



export default function Home() {
  const [repo, setRepo] = useState<Repository[]>([]);
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const [currentPage, setCurrentPage] = useState(1);
  const [reposPerPage, setReposPerPage] = useState(10);

  //fetch data
  useEffect(() => {
    setIsLoading(true);
    fetch("https://api.github.com/repositories")
      .then((resp) => resp.json())
      .then((data) => {
        setRepo(data);
        setIsLoading(false);
      });
  }, []);


  // Get current repos
  const indexOfLastRepo = currentPage * reposPerPage;
  const indexOfFirstRepo = indexOfLastRepo - reposPerPage;
  const currentRepo = repo.slice(indexOfFirstRepo, indexOfLastRepo);
  


  return (
    <>
      <Head>
        <title>Repository-page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <h1>Public Repository</h1>
          <Repos repos={currentRepo} loading={isLoading} />
          <Pagination reposPerPage={reposPerPage} totalRepos={repo.length} curPage={currentPage} setCurPage={setCurrentPage} />
        </div>
      </main>
    </>
  )
}
